name: Docs CI

on:
  push:
    branches: [ main, docs/ui ]
  pull_request:
    branches: [ main, docs/ui ]
  merge_group:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:check --if-present
        continue-on-error: true
      - run: npm run build --if-present